render 'Oblique' fonts
meyfa/php-svg pull request #236
Opened 2024-07-11 05:49 UTC by Tontyna

resolves  #235

2024-07-11 13:50 UTC, meyfa reviewed
Changes look good to me, thanks @Tontyna! Could you fix the indentation to make PHPCS happy?

2024-07-11 19:06 UTC, Tontyna commented
of course, if only I knew the rules...  Tried to guess.

2024-07-11 19:09 UTC, meyfa requested changes

2024-07-11 19:09 UTC, meyfa commented on src/Fonts/FontRegistry.php
> +            switch ($style){
```suggestion
            switch ($style) {
```

2024-07-11 19:09 UTC, meyfa commented on src/Fonts/FontRegistry.php
> +            $result = ($anyFontFamily || $font->getFamily() === $family);
There is a trailing space:

```suggestion
            $result = ($anyFontFamily || $font->getFamily() === $family);
```

2024-07-11 19:09 UTC, meyfa commented on src/Fonts/TrueTypeFontFile.php
> +            $this->subfamily === 'Bold' ||
Also one here:

```suggestion
            $this->subfamily === 'Bold' ||
```

2024-07-12 11:40 UTC, meyfa approved these changes

2024-07-12 11:40 UTC, merged

2024-07-12 11:43 UTC, meyfa commented
Thank you again for reporting this bug & also fixing it! This is now released as [v0.16.0](https://github.com/meyfa/php-svg/releases/tag/v0.16.0).